"use client";

import Link from "next/link";
import { assetUrl } from "@/lib/assets";
import { useEffect,useState } from "react";
import Icon from "@/components/learner/Icon";
import ChangePasswordForm from "@/components/ChangePasswordForm";
import { currentUser,getUsers,saveUsers,User } from "@/lib/store";

export default function ProfilePage(){const [user,setUser]=useState<User|null>(null);const [name,setName]=useState("");const [bio,setBio]=useState("");const [saved,setSaved]=useState(false);useEffect(()=>{const u=currentUser();setUser(u);setName(u?.name||"");setBio(u?.bio||"")},[]);function save(){if(!user)return;const next={...user,name,bio};saveUsers(getUsers().map(x=>x.id===user.id?next:x));localStorage.setItem("learnova_user",JSON.stringify(next));setUser(next);setSaved(true);setTimeout(()=>setSaved(false),2500)}function photo(e:React.ChangeEvent<HTMLInputElement>){const f=e.target.files?.[0];if(!f||!user)return;const r=new FileReader();r.onload=()=>setUser({...user,photo:String(r.result)});r.readAsDataURL(f)}if(!user)return null;return <div className="learnerPage"><section className="pageTitle"><div><p className="pageKicker">YOUR ACCOUNT</p><h1>Profile & preferences</h1><p>Keep your information and learning interests up to date.</p></div></section><div className="profileSettings"><aside className="panel profileIdentity"><div className="profilePhotoLarge">{user.photo?<img src={assetUrl(user.photo)} alt=""/>:user.name[0]}<label><Icon name="user" size={15}/><input hidden type="file" accept="image/*" onChange={photo}/></label></div><h2>{user.name}</h2><p>{user.email}</p><span>Learner</span><div className="profileCompletion"><div><b>Profile completion</b><strong>Your journey</strong></div><div><i/></div><small>Keep your learning goals up to date as your plans change.</small></div></aside><section className="panel profileForm"><div className="formSectionHead"><div><h2>Personal information</h2><p>How your profile appears across Learnova.</p></div>{saved&&<span className="savedMessage"><Icon name="check" size={14}/> Changes saved</span>}</div><div className="formTwo"><label>Full name<input value={name} onChange={e=>setName(e.target.value)}/></label><label>Email address<input disabled value={user.email}/></label></div><label>About me<textarea value={bio} onChange={e=>setBio(e.target.value)} placeholder="Tell specialists a little about you and what you want to achieve."/></label><div className="interestField"><b>Your learning preferences</b><p>Review and update your interests, goals, current stage, and preferred ways to learn.</p><Link className="learnerPrimary" href="/learner/onboarding">Edit learning preferences</Link></div><hr/><div className="preferenceBlock"><div><h3>Email notifications</h3><p>Receive session reminders and relevant updates.</p></div><label className="switch"><input type="checkbox" defaultChecked/><span/></label></div><div className="preferenceBlock"><div><h3>Community activity</h3><p>Notify me when someone replies to my posts.</p></div><label className="switch"><input type="checkbox" defaultChecked/><span/></label></div><div className="formFooter"><button className="learnerPrimary" onClick={save}>Save changes</button></div></section></div><ChangePasswordForm /></div>}
