"use client";

/**
 * Recommendation cards displayed inside the Learnova AI guidance chat.
 * Every card is built from a real database record returned by
 * POST /api/ai/chat — nothing here is generated by the AI.
 */

import Link from "next/link";

import { mediaUrl } from "@/lib/api";
import {
  AiPostRecommendation,
  AiRecommendations,
  AiSpecialistRecommendation,
  AiWorkshopRecommendation,
  formatDate,
  formatPrice,
} from "@/lib/ai";

/* ------------------------------------------------------------------ *
 * Specialist card
 * ------------------------------------------------------------------ */
export function SpecialistRecommendationCard({
  item,
}: {
  item: AiSpecialistRecommendation;
}) {
  const photo = mediaUrl(item.image);

  return (
    <article className="aiRecCard">
      <span className="aiRecBadge">🧑🏾‍🏫 Recommended specialist</span>

      <div className="profileRow">
        <div className="bigAvatar">
          {photo ? <img src={photo} alt={item.name} /> : item.name?.charAt(0) || "L"}
        </div>
        <div>
          <b>{item.name}</b>
          <small>{item.domain}</small>
          {item.verified && <span className="verified">✓ Verified specialist</span>}
        </div>
      </div>

      {item.specialization && (
        <p className="aiRecMeta">
          <strong>Specialization:</strong> {item.specialization}
        </p>
      )}

      {item.description && <p className="aiRecDesc">{item.description}</p>}

      {item.reason && <p className="aiRecReason">💡 {item.reason}</p>}

      <div className="aiRecActions">
        <Link className="primaryButton full" href={item.url}>
          View Profile
        </Link>

        <Link
          className="secondaryButton full"
          href={item.bookUrl || "/learner/specialists"}
        >
          Book Appointment
        </Link>
      </div>
    </article>
  );
}

/* ------------------------------------------------------------------ *
 * Workshop card
 * ------------------------------------------------------------------ */
export function WorkshopRecommendationCard({
  item,
}: {
  item: AiWorkshopRecommendation;
}) {
  const image = mediaUrl(item.image);
  const isPaid = item.type === "PAID";

  return (
    <article className="aiRecCard">
      {image && <img className="aiRecImage" src={image} alt={item.title} />}

      <div className="aiRecTopRow">
        <span className="aiRecBadge">🎓 Workshop</span>
        <span className={isPaid ? "aiPriceTag paid" : "aiPriceTag free"}>
          {isPaid ? formatPrice(item.price) || "PAID" : "FREE"}
        </span>
      </div>

      <h4 className="aiRecTitle">{item.title}</h4>

      <p className="aiRecMeta">
        <strong>Domain:</strong> {item.domain}
        {item.date ? ` · ${formatDate(item.date)}` : ""}
        {item.specialist ? ` · by ${item.specialist}` : ""}
      </p>

      {item.description && <p className="aiRecDesc">{item.description}</p>}

      {item.reason && <p className="aiRecReason">💡 {item.reason}</p>}

      <div className="aiRecActions">
        <Link className="primaryButton full" href={item.url}>
          View Workshop
        </Link>
      </div>
    </article>
  );
}

/* ------------------------------------------------------------------ *
 * Post card
 * ------------------------------------------------------------------ */
export function PostRecommendationCard({ item }: { item: AiPostRecommendation }) {
  const image = mediaUrl(item.image);

  return (
    <article className="aiRecCard">
      {image && <img className="aiRecImage" src={image} alt={item.title} />}

      <span className="aiRecBadge">📝 Community post</span>

      <h4 className="aiRecTitle">{item.title}</h4>

      <p className="aiRecMeta">
        <strong>By:</strong> {item.author || "Learnova specialist"}
        {item.domain ? ` · ${item.domain}` : ""}
      </p>

      {item.description && <p className="aiRecDesc">{item.description}</p>}

      {item.reason && <p className="aiRecReason">💡 {item.reason}</p>}

      <div className="aiRecActions">
        <Link className="primaryButton full" href={item.url}>
          View Post
        </Link>
      </div>
    </article>
  );
}

/* ------------------------------------------------------------------ *
 * Group renderer
 * ------------------------------------------------------------------ */
export default function RecommendationCards({
  recommendations,
}: {
  recommendations?: AiRecommendations | null;
}) {
  if (!recommendations) return null;

  const specialists = recommendations.specialists || [];
  const posts = recommendations.posts || [];
  const workshops = recommendations.workshops || [];

  if (!specialists.length && !posts.length && !workshops.length) return null;

  return (
    <div className="aiRecBlock">
      {specialists.length > 0 && (
        <div className="aiRecGroup">
          <h5 className="aiRecGroupTitle">Specialists who can help</h5>
          <div className="aiRecGrid">
            {specialists.map((item) => (
              <SpecialistRecommendationCard key={`specialist-${item.id}`} item={item} />
            ))}
          </div>
        </div>
      )}

      {workshops.length > 0 && (
        <div className="aiRecGroup">
          <h5 className="aiRecGroupTitle">Workshops to join</h5>
          <div className="aiRecGrid">
            {workshops.map((item) => (
              <WorkshopRecommendationCard key={`workshop-${item.id}`} item={item} />
            ))}
          </div>
        </div>
      )}

      {posts.length > 0 && (
        <div className="aiRecGroup">
          <h5 className="aiRecGroupTitle">Community posts to read</h5>
          <div className="aiRecGrid">
            {posts.map((item) => (
              <PostRecommendationCard key={`post-${item.id}`} item={item} />
            ))}
          </div>
        </div>
      )}
    </div>
  );
}
